/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ProductName]
      ,[AisleNumber]
  FROM [Shopping Application].[dbo].[Products]

INSERT INTO Products VALUES
('Bread', 1),
('Honey', 1),
('Jam', 1),
('Muesli Bars', 2),
('Gluten Free', 2),
('Vitamins', 2),
('Longlife Milk', 3),
('Cereal', 3),
('Coffee', 3),
('Lollies', 4),
('Chocolate', 4),
('Biscuits', 4),
('Juice', 5),
('Water', 5),
('Mixers', 5),
('Canned Fish', 6),
('Chips', 6),
('Sauce', 6),
('Asian', 7),
('Rice', 7),
('Pasta', 7),
('Canned Tomatoes', 7),
('Oil', 8),
('Baking', 8),
('Sugar', 8),
('Toilet Rolls', 9),
('Tissues', 9),
('Magazines', 9),
('Dental', 10),
('Haircare', 10),
('Shaving', 10),
('Baby', 11),
('Cosmetics', 11),
('Body Wash', 11),
('Dishwashing', 12),
('Cleaning', 12),
('Laundry', 12),
('Seasonal', 13),
('Dog Food', 13),
('Cat Food', 13),
('Block Cheese', 14),
('Pizza', 14),
('Ice Cream', 14),
('Frozen', 14),
('Butter', 14),
('Dips', 14),
('Platter Cheese', 14),
('Soft Cheese', 14)